### ISSUE TITLE
spectrum miss

### ISSUE THREAD

**Issue by LXP-Never** [SeventeenChen/Python_Speech_SZY#1]
where is spectrum

**Comment by SeventeenChen** [comment]
pr_2_4_1.py in Chapter 2
章节目录和宋知用老师的课本是对应的，后续会抽空完善整个repo的目录

**Comment by LXP-Never** [comment]
我通过pip install spectrum，找到了spectrum，感谢你的工作👍

**Comment by SeventeenChen** [comment]
感谢您的认可，共勉~
